### ISSUE TITLE
Add Pages menu to main menu

### ISSUE THREAD

**Issue by zolzaya** [MatthewKennedy/spree_pages#1]
Hi,
First of all thank you fro awesome extention. I have a question. How can I add Pages menu to main menu. It's not added automatically.

Thank for advise :D

**Comment by MatthewKennedy** [comment]
Hi @zolzaya 

I'll look into this now, just firing up a new fresh rails app.

Are you using this on its own or with the blogs extension?

**Comment by zolzaya** [comment]
@MatthewKennedy I using it with Action Text. I made some progress. I added following code to `initializers/spree.rb`

`Spree::BackendConfiguration::CONFIGURATION_TABS << :pages`

But it not **IN** the Configurations menu, It's **IN** the main menu. It's look like bug of `Spree`

**Comment by MatthewKennedy** [comment]
I updated the extension as deface is not in Spree by default so the override was not being picked up.

**Comment by zolzaya** [comment]
@MatthewKennedy oh ok. I get another problem. When I set `SpreePages::Config.use_action_text = true` and I added Action Text with js, css. It's not display in new Page.

**Comment by zolzaya** [comment]
@MatthewKennedy should I add `has_rich_text :content` to Page model?

**Comment by MatthewKennedy** [comment]
Hi @zolzaya 

From the root of your app run: `bin/rails action_text:install` To install action text.

In:
`your_app/vendor/assets/sytlessheets/spree/backend/all.css`
Add at the top `//= require actiontext`

In:
`your_app/vendor/assets/sytlessheets/spree/frontend/all.css`
add at the top `//= require actiontext`


Additionally add this to application.rb:
```ruby
    # Configs for action_text in Spree.
    config.action_view.sanitized_allowed_tags = ["strong", "em", "b", "i", "p", "pre", "hr", "br", "div", "span",
      "h1", "h2", "h3", "h4", "h5", "h6", "ul", "ol", "li", "a", "img",
      "blockquote"]

    config.action_view.sanitized_allowed_attributes = ["href", "src", "width", "height",
      "alt", "title", "class", "id", "name"]
```

**Comment by zolzaya** [comment]
@MatthewKennedy thanks for help. Already added but result is the same. I also run `rails assets:clobber`, `rake tmp:clear` and re-compile assets. But no luck :(

**Comment by zolzaya** [comment]
@MatthewKennedy I just found it. App says 
`ActionController::RoutingError (No route matches [GET] "/assets/spree/backend/trix/dist/trix"):`
Where can I add it?

I added following code to actiontext.css NOT scss.
`@import "trix/dist/trix";`

**Comment by zolzaya** [comment]
OKay I just make it work. Thank for help @MatthewKennedy

**Comment by MatthewKennedy** [comment]
I think also you need to add:

`<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>`

in the admin head to pull in the javascript.

I wish I had documented what I did.

**Comment by MatthewKennedy** [comment]
Let me know if it's fully working.

**Comment by MatthewKennedy** [comment]
@zolzaya 
Bingo!!

<img width="1212" alt="Screenshot 2021-03-09 at 13 30 18" src="https://user-images.githubusercontent.com/1240766/110477922-a935ca80-80db-11eb-9407-20c2cc1d6a65.png">

I'' add documentation now before I forget.

**Comment by zolzaya** [comment]
@MatthewKennedy please document it 💪💪💪

**Comment by MatthewKennedy** [comment]
Hi @zolzaya 

I have written a [guide](https://github.com/MatthewKennedy/spree_pages/blob/main/spree_actiontext.md), if you want to take a look let me know if it works or not, and if I can make it any easier to understand
